### ISSUE TITLE
Cannot get any modifier key actions to work (v 6.5, os x 10.11.6)

### ISSUE THREAD

**Issue by arooni** [vdesabou/alfred-spotify-mini-player#148] opened 2016-10-24 17:29 UTC
I love your app; but whenever I use your player I try:
- Invoke with spot_mini 
- See the "Begin typing at least 3 characters ...'
- Hold down function key
- See the text change to "Add track to Alfred Playlist"
- Hit return (while holding down function key)
- Nothing happens.  

Same happens with any of the other modifier keys (Command, shift, etc).  I am using a Windows Keyboard (Microsoft Sculpt) but I have never had any issues before.

I'm sure I'm doing something wrong, but what it is it?  

I did try searching Google before posting.

**Comment by vdesabou** [comment] 2016-10-25 13:15
Looks like you do not select a track before invoking the modifier key.. More info here http://alfred-spotify-mini-player.com/articles/modifier-keys/

**Comment by vdesabou** [comment] 2016-10-25 18:31
I think you need to do it when a song is selected, see 
http://alfred-spotify-mini-player.com/articles/modifier-keys/

Vincent

**Comment by arooni** [comment] 2016-10-25 18:56
![image](https://cloud.githubusercontent.com/assets/556667/19699871/a20fe544-9aba-11e6-8e88-4e685cafac86.png)

![image](https://cloud.githubusercontent.com/assets/556667/19699859/9a274930-9aba-11e6-92a8-8574e49155c2.png)

I am pretty sure I've selected the track, but once I try *any* other option other than "Play album/track in spotify" I get screenshot #2.  Ideas?

**Comment by vdesabou** [comment] 2016-10-26 12:42
I do reproduce an issue with ```fn``` modifier: it pauses the song rather than calling the Add to option
However, other modifiers are working as expected.

From the screenshots, I can see that you're using 's' to call the workflow, but when 'Add To' is called, it is using default 'spot_mini'.

How did you redefine 's' command ?

Did you follow procedure in https://github.com/vdesabou/alfred-spotify-mini-player/issues/132 ?

**Comment by vdesabou** [comment] 2016-10-27 12:24
>I do reproduce an issue with fn modifier: it pauses the song rather than calling the Add to option
This is a bug in alfred, see http://www.alfredforum.com/topic/9659-fn-modifier-broken-accepted/#comment-48320

For your problem, I think you renamed spot_mini to s without using variables, hence your issues. Renaming of commands should be done using Variables

**Comment by arooni** [comment] 2016-10-28 19:50
Thanks for the quick response!  

So I reverted the main command from s ==> spot_mini.  I did notice a change in that after whatever function key + return, I no longer get that giberish at the beginning but now, spot_mini doesn't seem to do anything; 

I.e.. select current track
Hold down any key (say shift)
-- prompt changes to add album to alfred playlist -- 
Hit enter.
Nothing happens 

Ideas?

Thanks so much !

**Comment by vdesabou** [comment] 2016-10-29 09:34
I would suggest you re-download and install the workflow from http://alfred-spotify-mini-player.com 
If it still does not work after that, then follow this http://alfred-spotify-mini-player.com/articles/support/ in order to send me TGZ file.

**Comment by vdesabou** [comment] 2016-11-03 09:17
@arooni any feedback ? Can I close this ticket ?

**Closed** 2016-11-07 15:53 UTC
Labels: question
