### ISSUE TITLE
404 error for a playlist

### ISSUE THREAD

**Issue by BenJP51** [vdesabou/alfred-spotify-mini-player#168] opened 2017-01-29 19:21 UTC
I saw this issue was happening, but the problem was 'resolved' about a year ago. It's happening to me right now. I'm running: 

Spot_Mini v7.0, Alfred v3.2.1, MacOS v10.12.3
Let me know if there is a way to update or fix this. Thanks.

**Comment by vdesabou** [comment] 2017-01-30 08:39
Can you send me a ZIP file by email as explained here http://alfred-spotify-mini-player.com/articles/support/

**Comment by vdesabou** [comment] 2017-02-03 11:31
Any feedback before I close the issue?

**Comment by BenJP51** [comment] 2017-02-04 07:05
Yes, I emailed the zip to you.

**Comment by vdesabou** [comment] 2017-02-05 19:25
The problem is Spotify web api returning this uri `spotify:user:spotify:playlist:37i9dQZF1DXecP5TUr7X2d`whereas it should be `spotify:user:12151559079:playlist:60DaqmQgpKHl2GbadxAWtW`
It gives 404 error not found error. I'll update workflow to handle this case.

**Closed** 2017-02-18 11:36 UTC
Labels: bug
