### ISSUE TITLE
Adding track to playlist triggers refresh of entire library

### ISSUE THREAD

**Issue by stephenkirk** [vdesabou/alfred-spotify-mini-player#328] opened 2020-03-02 16:59 UTC
When adding the currently playing track to a playlist, using either the Alfred UI, or the AppleScript api (`add_current_track_to`), seems to trigger a refresh of all playlists in the library. As I have hundreds of playlists, this can take minutes. During this time, I am unable to add tracks to the library.

Perhaps it would be enough with a partial update for the target playlist only?

**Comment by adddz** [comment] 2020-04-15 00:26
I totally agree on this. It also happens when I am adding the current track to the Alfred playlist. I cannot add other tracks during that time. I have many playlists (40-50) and this makes it unusable.

Could you please add the option to NOT refresh the entire library everytime we add a track to a playlist or to the current Alfred playlist? It would be amazing.

**Comment by vdesabou** [comment] 2020-04-15 16:26
This behaviour is expected because I want to refresh the local library as much as possible. However, I'm surprised it takes minutes in your case because I only refresh playlists that have changed. If there is no change to other playlists, only the playlist for which you added the track would be refreshed.

In my case, If I add a track to a playlist, it takes less than 20 seconds to refresh the library afterwards

But maybe you have a lot of playlists that auto-update ?

I'll not make a change to only update the playlist that has changed, as it would take too much time to implement.

However, I'll add an environment variable `automatically_refresh_library`(default to 1), that you could set to 0 to avoid to auto update. In that case you'll be able to update the library only when you want to

This will be included in 9.0 release

**Comment by adddz** [comment] 2020-04-16 00:22
I think it greatly depends from the use case.
Sometimes I find myself listening to a track, adding it to the Alfred playlist and after few seconds skip to the next track and add again. That's why even 20 seconds can be too long and it prevents from adding new tracks until the refresh is finished.

The environment variable will be MUCH appreciate. Will wait for it and thank you!

**Comment by stephenkirk** [comment] 2020-04-20 08:45
> This behaviour is expected because I want to refresh the local library as much as possible. However, I'm surprised it takes minutes in your case because I only refresh playlists that have changed. If there is no change to other playlists, only the playlist for which you added the track would be refreshed.
> 
> In my case, If I add a track to a playlist, it takes less than 20 seconds to refresh the library afterwards
> 
> But maybe you have a lot of playlists that auto-update ?

Correct - I have 380 playlists, where some of these are playlists I am subscribed to and therefore presumably are changed a lot more often. However, even just after a library refresh, there's probably a full 30-60 seconds before I can add tracks to a playlist. Miniplayer always adds the track instantly to the playlist, but then there's the wait period until I get the notification that it has updated the playlist in question and I can manipulate playlists again. 

I notice that it quite often tells me that another playlist that I haven't touched since 2017 was updated in the library refresh. Perhaps this is a separate issue?
![image](https://user-images.githubusercontent.com/5837934/79732122-88ae2780-82f3-11ea-9e80-7cab835dc263.png)

> I'll not make a change to only update the playlist that has changed, as it would take too much time to implement.
> 
> However, I'll add an environment variable `automatically_refresh_library`(default to 1), that you could set to 0 to avoid to auto update. In that case you'll be able to update the library only when you want to
> 
> This will be included in 9.0 release

This would be very appreciated and would allow me to work around it. Thank you!

**Comment by vdesabou** [comment] 2020-04-21 10:35
@stephenkirk Would you mind sending me a debug zip file by email as explained in here http://alfred-spotify-mini-player.com/articles/support/ ?

I would then be able to reproduce and see what's going on on my side

**Comment by vdesabou** [comment] 2020-04-26 14:25
This is now available in version 9.0 https://alfred-spotify-mini-player.com/blog/Version-9.0/

**Closed by vdesabou** 2020-04-26 14:25 UTC
Labels: enhancement, feature request

**Comment by gimbo** [comment] 2021-07-02 14:25
I realise this is closed, and I'm very pleased to see the `automatically_refresh_library` option, because that gives me a good workaround, but I just wanted to note that I was hitting this too, in a slightly different way, and was initially going to open a new issue, but then I saw this. That option really helps me, but just to add some data...

I was hitting this when *removing* a track from a playlist. In particular, I have a "Discovery Queue" playlist, into which I copy my "Discovery Weekly" every week (so it starts out as just those tracks). Then I refresh my library, start listening, and remove tracks I don't like — this is how I pick out stuff I like from Discover Weekly and copy it elsewhere.

Anyway, **very** often I'll remove a track, start listening to the next one, and very quickly realise I want to remove that too — often within a few seconds. But (without `automatically_refresh_library`, yay), I had to wait for the refresh to finish before removing that second track. So, a similar issue to what's described above, but different because removing (and often in quite quick succession because of that).

Refreshing my library takes about a minute each time; 135 playlists, so not huge. While it's going it definitely reports (in the "Refresh library in progress" display) that it's processing playlists which **aren't** auto-updaters — but maybe that's just it checking if they've changed? Either way, it's definitely got slower as I've added more playlists, but yes, some of them are auto-updating.

> I'll not make a change to only update the playlist that has changed, as it would take too much time to implement.

Fair enough, and thanks enormously for this great workflow — I'm going to go and buy you a beer now., because I've been using this for a few years now (and was never quite annoyed enough by this problem to report it until today 😀 ).
