### ISSUE TITLE
Quick Mode not working

### ISSUE THREAD

**Issue by asumawang** [vdesabou/alfred-spotify-mini-player#272] opened 2019-01-09 05:18 UTC
Quick Mode is enabled but upon typing a song, it does not display even after waiting for a few minutes.
I'm using v7.19 and Alfred v3.7.1

Please help. Thanks!

**Comment by vdesabou** [comment] 2019-01-09 08:50
Can you send me debug zip file by email as explained [here](http://alfred-spotify-mini-player.com/articles/support/)
So when you select a song with quick mode, it does not launch it in Spotify ?

**Comment by asumawang** [comment] 2019-01-09 23:53
Sent. The issue is that songs (or any results) does not appear in quick mode. Thanks!

**Comment by vdesabou** [comment] 2019-01-15 09:02
@asumawang any feedback ? I'll close the ticket otherwise. Thanks

**Comment by vdesabou** [comment] 2019-01-16 07:19
Hmm it looks like you are not using the workflow when typing foo fighter..I guess it is the first time you are using it?
You need to invoke the workflow first by typing spot_mini in Alfred and then foo fighter. It is recommended to use an hotkey to invoke the workflow, see http://alfred-spotify-mini-player.com/articles/hotkeys/

**Comment by asumawang** [comment] 2019-01-16 10:05
I've used it before and I actually used the workflow before and I've done what you've mentioned.

it's just that Quick Mode does not work.

**Comment by vdesabou** [comment] 2019-01-16 10:15
it's confusing because you were saying "No results when Quick Mode is not enabled (disabled)", so it seems to me it's not working at all..?

Can you show me the debug output as before using "spot_mini foo fighters"

**Comment by asumawang** [comment] 2019-01-16 23:55
> it's confusing because you were saying "No results when Quick Mode is not enabled (disabled)", so it seems to me it's not working at all..?

Sorry for the misunderstanding, search is working with the spotify_mini keyword entered. I just thought you wanted to check what happens when there is no 'spotify_mini' keyword entered when you said:
>So to understand better the problem, when Quick Mode is not enabled, a search is working fine, i.e you see results like this


debug output as before using "spot_mini foo fighters":

[spotify_mini_debug.txt](https://github.com/vdesabou/alfred-spotify-mini-player/files/2766565/spotify_mini_debug.txt)

Thanks for patiently helping me out with this, I appreciate it. I just wanted Quick Mode to work that's all.

**Comment by asumawang** [comment] 2019-01-17 00:53
@vdesabou thanks a lot for your help. If you want to continue troubleshooting I can help. I settled using a hotkey though. Again, I appreciate your effort and for this wonderful workflow. All the best.

**Comment by vdesabou** [comment] 2019-01-17 08:16
Ok thanks for the information, don't worry I'll continue to help you until we figure out what's going on.

I checked the debug output and everything seems fine. That's weird, you should normally see some results and not the default Google Search result you showed me earlier.

Can you try to install this small workflow and type in Alfred "jsonformat"

[repro.alfredworkflow.zip](https://github.com/vdesabou/alfred-spotify-mini-player/files/2767619/repro.alfredworkflow.zip)

You should normally see this:

![screenshot 2019-01-17 at 09 09 25](https://user-images.githubusercontent.com/4061923/51304327-21426180-1a38-11e9-8dd6-22bb3f361e54.jpg)

Let me know what you get in your case

**Comment by vdesabou** [comment] 2019-01-18 07:53
ok thanks.
So I have tried to installed your library in my environment (with the debug file you sent earlier) and I can see results with no problem , see:

![screenshot 2019-01-18 at 08 49 03](https://user-images.githubusercontent.com/4061923/51372621-16520480-1afe-11e9-9f5a-9841c9b3f4f2.jpg)

I don't understand what's going on. Normally if we see google result like you do, it means that JSON output is not valid, but we have checked that it is valid. It's not something weird in characters as well because you can display results with the test from above..

Would you be able to record your screen when you reproduce the issue, so that I'm 100% of what is exactly the problem ?

**Comment by asumawang** [comment] 2019-01-21 00:08
I can actually see results when using the keyword spotify_mini <search string> but I don't see any results when using Quick Mode: https://youtu.be/LBli3h2NBb4

**Comment by vdesabou** [comment] 2019-02-05 07:38
Closing as no feedback. Re-open if needed

**Closed by vdesabou** 2019-02-05 07:38 UTC
Labels: feedback requested
