### ISSUE TITLE
Notification area Show button

### ISSUE THREAD

**Issue by FleXoft** [vdesabou/alfred-spotify-mini-player#583] opened 2022-10-23 10:37 UTC
When I click the "**Show**" button on the Notification message, something seems to happen on the Dock, but really nothing.
Should something happen? 

// Latest Monterey + Spotifiy + Mini player.

**Comment by FleXoft** [comment] 2022-10-26 16:58
I went through the previous issues and same behaviour [has occurred](https://github.com/vdesabou/alfred-spotify-mini-player/issues/465) before with no solution.

Can I give you some help to  debug it?

**Comment by vdesabou** [comment] 2022-10-28 06:24
Thanks. I can also reproduce same issue.
It is supposed to open Spotify desktop normally.
Just need to find some time to understand why it is no more working..

**Comment by vdesabou** [comment] 2023-04-28 08:44
Closing as I'm using https://github.com/vitorgalvao/notificator since version 13.0

**Closed by vdesabou** 2023-04-28 08:44 UTC

**Comment by FleXoft** [comment] 2023-04-30 12:13
Still nothing happens when I click on the **Show** button in the notification bubble...
