### ISSUE TITLE
Sorting features don't work with mini player

### ISSUE THREAD

**Issue by SoPat712** [vdesabou/alfred-spotify-mini-player#395] opened 2020-09-02 15:43 UTC
My Alfred playlist is a 200 song playlist that I created for myself. I sort by recently added, and I like to listen to the songs in recently added order. The problem is with the order in which it plays. Even though the Alfred playlist shows the order of the songs in recently added, it goes backwards, going up the list instead of down it. This means that the recently added sort doesn't work, and the majority of the reason I use the app itself is nullified. I would really appreciate if sorting features worked on the Alfred playlist as well. 

Hope to hear from you soon.

**Comment by vdesabou** [comment] 2020-09-03 07:10
When the workflow is starting a playlist, it has no way to specify an order. The order of songs should be the same as what is displayed in your Spotify Desktop app, example:

![Screenshot 2020-09-03 at 09 06 44](https://user-images.githubusercontent.com/4061923/92082430-d324d200-edc4-11ea-8bf7-fd3cc43f819f.png)

First song started will be "THE FLAME".

When you add a song to a playlist with the workflow, you can choose if this is appended or prepended, as explained [here](https://alfred-spotify-mini-player.com/articles/customization/):

![Screenshot 2020-09-03 at 09 07 56](https://user-images.githubusercontent.com/4061923/92082670-2434c600-edc5-11ea-89e0-170e2468a20a.png)

Can you check the order that you see in Spotify Desktop ?

**Comment by vdesabou** [comment] 2020-09-07 06:25
@SoPat712 Any feedback ? Can you check my previous comment? Thanks

**Comment by SoPat712** [comment] 2020-09-07 11:49
Hi, the order is displayed correctly in spotify mini player. It's just that the songs don't continue in the right direction. Imagine a 2 song playlist. 1 is first, and 2 is recently added. I want to play 2, then 1. Instead spotify mini player plays 2, then plays similar songs because the playlist is apparently over. If I choose 1, when the playlist is sorted as 2,1 in that order, the songs will play in the order 1,2 even though I see the order 2,1. How would I be able to switch the order of the entire playlist to fix this, because my playlist is 900 songs long now.

**Comment by vdesabou** [comment] 2020-09-07 11:53
@SoPat712 I did not ask the order in spotify mini player, but in Spotify Desktop instead. Can you please check that

**Comment by SoPat712** [comment] 2020-09-07 11:54
Spotify desktop shows the order in recently added meaning I see the songs as 3,2,1.

**Comment by SoPat712** [comment] 2020-09-07 11:55
I can send a video describing the problem, that might make it easier.

**Comment by vdesabou** [comment] 2020-09-07 12:11
Yes a video could help, but in term of what the workflow can do or not: when a playlist is started, there is no way to specify the order, so it will just play the playlist in the order presented in Spotify Desktop. I'll investigate based on your video, but I doubt there is something that can be done on my side

Also, are you sure shuffle is not activated ?

**Comment by SoPat712** [comment] 2020-09-09 12:07
I am sure that shuffle is not activated. That's the problem. It's not playing on the order specified in spotify desktop, it's playing backwards. That's the main issue.

**Comment by vdesabou** [comment] 2020-09-09 13:12
@SoPat712 I cannot reproduce your issue, for me it works as expected:

![2020-09-09 14-38-59 2020-09-09 14_42_11](https://user-images.githubusercontent.com/4061923/92602511-8488a380-f2ae-11ea-9fa8-fcc6e0bd5ffe.gif)

send me a video of what you see

**Comment by SoPat712** [comment] 2020-09-09 13:22
What you did in the gif was reordering. Click the calendar button on spotify to sort the playlist by songs that you added most recently.

**Comment by SoPat712** [comment] 2020-09-09 13:22
I will record a video ASAP and send it here.

**Comment by vdesabou** [comment] 2020-09-09 14:03
Sorting the playlist with filters in Spotify Desktop does not change anything for me.

In a terminal, you can execute the following

```
osascript -e 'tell application "Spotify" to play track "spotify:playlist:37i9dQZF1DWXRqgorJj26U"'
```

![Screenshot 2020-09-09 at 15 58 35](https://user-images.githubusercontent.com/4061923/92608228-61152700-f2b5-11ea-83ec-26aa2842327b.png)

It will always play the first song at the top (with no filter applied), i.e Whole Lotta Love", even though some songs were added more recently. So it is the order in Spotify Desktop that counts

Again, the workflow is just starting the playlist, so in any case, I can do something to change the order.

When a song is added by the workflow, it is put at the top of playlist, so it will be played first. You can put it at the end by modifying variable `append_to_playlist_when_adding_tracks` as explained earlier

**Comment by SoPat712** [comment] 2020-09-12 19:13
I'm not sure if you will be able to tell the problem here from this video, but I hope you can tell.

https://streamable.com/mme77a


My goal is simply to have the song Mood played first, because it is the most recent song I added, and I want the playlist to be played in the order visible on Spotify, by going down. The terminal command you gave me doesn't account for the ordering done in Spotify Desktop, but apparently spotify-mini-player takes the order and properly DISPLAYS it, but doesn't PLAY the songs in the order displayed. The playlist simply plays in the wrong order, regardless of the way that it is displayed in spotify-mini-player. If you still don't understand, don't hesitate to ask more questions.

**Comment by vdesabou** [comment] 2020-09-14 07:22
When the workflow starts the playlist (it does `osascript -e 'tell application "Spotify" to play track "spotify:playlist:xxxx"'`, it will be in the order that is displayed when the playlist is displayed in Spotify Desktop:

<img width="1405" alt="Screenshot 2020-09-14 at 09 14 02" src="https://user-images.githubusercontent.com/4061923/93055165-c88ef600-f66a-11ea-9b45-6e52402db05f.png">

**There is no way I can change that, it is out of my control.**

If you're the owner of the playlist, you can reorder the tracks.
If you're not the owner, you will need to duplicate the playlist and re-order according to your needs.

Personally when I add a track to a playlist, it is put at bottom (because `append_to_playlist_when_adding_tracks=0`), and so when I start the playlist, it plays latest added tracks first

**Comment by vdesabou** [comment] 2020-09-26 15:59
Closing as nothing can be done at workflow level

**Closed by vdesabou** 2020-09-26 15:59 UTC
