### ISSUE TITLE
Play Track for Local files not working due to applescript bug

### ISSUE THREAD

**Issue by zucram** [vdesabou/alfred-spotify-mini-player#82] opened 2015-05-27 12:11 UTC
Hi!
I've added some new local tracks and recreated my library but the player won't let me play them. They show up but there is a red stop sign in front of them, se screenshot. 

![skarmavbild 2015-05-27 kl 14 10 28](https://cloud.githubusercontent.com/assets/5426869/7835563/45d39e10-047a-11e5-8c0e-0dcfeaebab26.png)

**Comment by vdesabou** [comment] 2015-05-27 12:24
Hi,

Can you provide TGZ file by email as described here http://alfred-spotify-mini-player.com/articles/support/ ?

Are you using the workflow with Mopidy ?

**Comment by zucram** [comment] 2015-05-27 12:26
Hi!
Not using mobidy. 
All other local tracks work fine. Just not the ones i imported today. 


/Marcus

**Comment by vdesabou** [comment] 2015-05-27 12:35
ok, but without TGZ file, I cannot help...

**Comment by zucram** [comment] 2015-05-27 12:36
i attached it to the previous email….

/Marcus

**Comment by vdesabou** [comment] 2015-05-27 12:37
Github does not allow attachments. Use the email address in http://alfred-spotify-mini-player.com/articles/support/

**Comment by vdesabou** [comment] 2015-05-27 13:00
I can see that the tracks causing issue are from this playlist https://open.spotify.com/user/jackrabbit/playlist/0SSWJDjxQcwOMLLjh9leX8 

Is that correct ?

Because it looks empty, which is strange because in your library i can see tracks in it, however they're not marked as local tracks, but instead as regular tracks, but Taylor Swift removed her album from Spotify:

![capture d ecran 2015-05-27 a 14 51 53](https://cloud.githubusercontent.com/assets/4061923/7836368/f6320c38-047f-11e5-810a-962a907ff7c8.png)

Hence that's why the tracks are marked not playable and you get the red sign.

Can you then confirm that you are really using local tracks?

**Comment by zucram** [comment] 2015-05-27 13:12
Hi!
In my playlist they appear as white and not grey, and i can play them so i assume they are playing localy since, as you say, taylor swift is not available on spotify. I’ve tried removing the playlist and recreating the library and i can still play the songs from within spotify when searching for taylor swift but not from the mini player. They show up with the red stop sign still.

**Comment by vdesabou** [comment] 2015-05-27 13:14
Do you see these tracks in Spotify in the 'Local Files' tab ?

**Comment by zucram** [comment] 2015-05-27 13:14
Yes!

**Comment by vdesabou** [comment] 2015-05-27 14:50
Can you try to create a new playlist, drag local tracks from Local Files tab to the new playlist and then refresh the library ?

Then if you have same issue, let me know

**Comment by zucram** [comment] 2015-05-27 14:56
Hm. That seems to have done ”something”. They songes are now shown with the ”pin” in the player but they will not start playing when i press enter.

**Comment by vdesabou** [comment] 2015-05-27 15:35
I can reproduce the problem. Looks like it is another bug with Spotify desktop and applescript support because when we try to play a local track using applescript, it does nothing:

Example:

```
osascript -e 'tell application "Spotify" to play track "spotify:local:Damien+Rice:B-Sides:Woman+Like+a+Man:284"'
```

or in your case:

```
osascript -e 'tell application "Spotify" to play track "spotify:local:Taylor+Swift:1989:Blank+Space:231"'
```

I will report this to Spotify

**Comment by vdesabou** [comment] 2015-05-31 09:48
Issue reported to Spotify [here](https://community.spotify.com/t5/Help-Desktop-Linux-Mac-Windows/AppleScript-play-track-not-working-with-local-tracks/m-p/1143252#M129641)

**Closed** 2016-09-28 15:17 UTC
Labels: bug, known issue
