### ISSUE TITLE
Initial library update never completes

### ISSUE THREAD

**Issue by nsh87** [vdesabou/alfred-spotify-mini-player#38] opened 2015-01-21 15:03 UTC
My initial library update never finished. None of the `spot_mini_*` commands work. I tried removing the workflow and re-adding it after restarting but just get the same *Library update in progress* at track 1300.
![screen shot 2015-01-21 at 7 00 49 am](https://cloud.githubusercontent.com/assets/4327717/5838305/580154d0-a13b-11e4-8a0b-bb4394493851.png)

**Comment by nsh87** [comment] 2015-01-21 15:07
Duplicate of issue #22. Closing.

**Comment by vdesabou** [comment] 2015-01-21 15:09
Hi, 

I'm not sure it is a duplicate of #22 !
Can you follow instructions from here http://alfred-spotify-mini-player.com/articles/support/ (create TGZ file and send it to email on my profile) ?

I'll have a look

**Comment by nsh87** [comment] 2015-01-21 15:12
Ya, sure, just sent it. Not sure if it was created before or after I killed everything. I have the initial update going again after following some steps in #22. On track 620 right now. I'll report back if it stops at 1300 again.

**Comment by vdesabou** [comment] 2015-01-21 15:32
Thanks for the TGZ. So that's what I thought, you have the bug described in #37 
And unfortunately, you will have to wait version 6.0 (which is described in details [here](http://alfred-spotify-mini-player.com/) but not released yet. I need to wait the next version of Alfred to be released ....

**Comment by nsh87** [comment] 2015-01-21 16:29
Ah, thanks for looking into it. I got 2140/2193 indexed somehow, then it stopped again lol. So close. I'll get 6.0 when it comes out. Thanks.

**Comment by vdesabou** [comment] 2015-01-21 16:36
Yes it depends when the token from spotify is refreshed...It does not help
much, but I know how to explain this :)
At least you can enjoy a good part of your music

On Wed, Jan 21, 2015 at 5:29 PM, Nikhil Haas <notifications@github.com>
wrote:

> Ah, thanks for looking into it. I got 2140/2193 indexed somehow, then it
> stopped again lol. So close. I'll get 6.0 when it comes out. Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vdesabou/alfred-spotify-mini-player/issues/38#issuecomment-70869436>
> .
>



-- 
Vincent

**Comment by vdesabou** [comment] 2015-01-27 17:57
Version 6.0 is now live. It will fix this issue. Get it here http://alfred-spotify-mini-player.com

**Closed by vdesabou** 2015-01-27 17:57 UTC
Labels: bug
