### ISSUE TITLE
Spotfify Mini-Player Alfred Workflow

### ISSUE THREAD

**Issue by alfwork** [vdesabou/alfred-spotify-mini-player#58] opened 2015-02-15 15:01 UTC
Hi

I am having a problem with this workflow for Alfred v2. I tried to setup the whole Client Id thing, to make it work, but I think I might have swithed the "Client ID" and the "Secret Client ID", and I cant seem to change it again, even if I uninstall it, and reinstall it. 

I hope you can help med with this. 

/Daniel Andersen

**Comment by vdesabou** [comment] 2015-02-15 16:06
Hello,

Open Alfred window and type ```spot_mini_reset_settings```
That will reset your settings and you can do auth process again.

**Comment by alfwork** [comment] 2015-02-15 16:15
Hi, 
 
I've already tried this, and I even tried to restart Alfred, but it didn't change anything I can still only do the authentication process.. 

/Daniel

**Comment by vdesabou** [comment] 2015-02-15 16:28
>I can still only do the authentication process..

I thought that was the goal of your question: to be able to do the auth process again so that you can fix the client secret and client id..
Can you please describe exactly what's the problem then, what you see?

Also send me a TGZ file as described here http://alfred-spotify-mini-player.com/articles/support/

**Comment by alfwork** [comment] 2015-02-15 16:44
It is my goal to do the authentication process again, but first I need the change the Client ID's? If I try to authenticate at this points, I just get an error, (404 - Not found (The requested resource / was not found on this server.)). I should also say I have remade the Spotify application, to get new Client ID's. 

I will send you the TGZ file, but what exactly does it contain?

**Comment by vdesabou** [comment] 2015-02-15 16:48
First install this version of the workflow please: http://inft.ly/x6bQtFF

After executing ```spot_mini_reset_settings```, when you invoke the workflow again, you should be presented with the option to set client Id again, isn't it the case?

If it is not the case let me know, as it means there is a problem with the command.

**Comment by alfwork** [comment] 2015-02-15 16:57
Hi

I did as you told me, and I tried to reset the settings again. But I still only have the option to authenticate with Spotify. Tho I got a new error now (INVALID_CLIENT: Failed to get client). I hope you can use this. 

/Daniel

**Comment by vdesabou** [comment] 2015-02-16 16:52
Ok Thanks.

spot_mini_reset_settings should work as it deletes the settings.son file...Did you get by any chance a notification saying that it could not be deleted?
Can you send the TGZ file when you execute this command?

As a workaround, you can delete the file by invoking spot_mini_debug and then browse to App Support folder and then delete settings.son file.

Then invoke workflow again and follow auth process. That should work this time

**Comment by alfwork** [comment] 2015-02-16 18:51
No sry, I did not get any notification about that. 
But I tried to delete the settings.json file, which fixed the problem! 

Thanks you!

**Comment by alfwork** [comment] 2015-02-16 18:56
When you authenticate to Spotify (Which all works fine) - You have to accepts a whole list of things. One of them is: Giving Alfred Spotify Workflow access to my subscription details? - Is this only the date and stuff, or also creditcard information??

/Daniel

**Comment by vdesabou** [comment] 2015-02-16 19:45
> When you authenticate to Spotify (Which all works fine) - You have to accepts a whole list of things. One of them is: Giving Alfred Spotify Workflow access to my subscription details? - Is this only the date and stuff, or also creditcard information??

No don't worry, there is no credit card information, or your password of course ! In any case, I don't use in any way private information, I don't have it anyway :smile:
The only time I can have access to private information is when the user send me TGZ file for troubleshooting, and this is explained in the blue note here http://alfred-spotify-mini-player.com/articles/support/

If you want to read more about privacy scope, I'm using:-

```
					'user-library-read',
					'user-read-email',
					'user-read-private',
					'user-library-modify',
					'user-follow-modify',
					'user-follow-read',
					'playlist-read-private',
					'playlist-modify-public',
					'playlist-modify-private'
```

Which are described here https://developer.spotify.com/web-api/using-scopes/

**Comment by vdesabou** [comment] 2015-02-16 19:46
>No sry, I did not get any notification about that. 

Strange..Can you confirm that you were using version from the link I gave above (http://inft.ly/x6bQtFF) ?

**Comment by alfwork** [comment] 2015-02-16 19:59
Alrigth great. 

Yes I deletes the entire workflow, and installed the one you linked to me ;)

The entire thing is working as well now :)

**Comment by vdesabou** [comment] 2015-02-16 20:01
Ok thanks for feedback, I still don't get why ```spot_mini_reset_settings```is not working for some people. 
But I'm going to close this issue now.

Enjoy the workflow

**Comment by vdesabou** [comment] 2015-02-16 20:02
Duplicate of https://github.com/vdesabou/alfred-spotify-mini-player/issues/56

**Closed by vdesabou** 2015-02-16 20:01 UTC
Labels: bug

**Comment by alfwork** [comment] 2015-02-16 20:03
Alright thanks for the help tho! :)
