### ISSUE TITLE
Lyrics Search not working?

### ISSUE THREAD

**Issue by deusy** [vdesabou/alfred-spotify-mini-player#64] opened 2015-03-01 00:37 UTC
When I do a lyrics search, Alfred closes and then reopens with "spot_mini Lyrics▹spotify:track:number∙artist∙song". It then just sits there with my fallback searches. Am I doing something wrong?

I have the latest version of the workflow, and it wasn't working before I updated either. Any help is appreciated. :-)

**Comment by vdesabou** [comment] 2015-03-01 09:31
Hi,

Can you send the output of Alfred Debug output (go to the workflow in Alfred and click debug button) when you get the problem?

Vincent

**Comment by deusy** [comment] 2015-03-01 23:26
Hey, thanks for the quick reply,
I ran the debug to log all information and did a lyrics search for the song I was listening to. I just received:

Starting debug for 'Spotify Mini Player'

[INFO: alfred.workflow.input.keyword] Processing output 'alfred.workflow.action.script' with arg ‘'

Cheers.

**Comment by vdesabou** [comment] 2015-03-03 11:23
```
[INFO: alfred.workflow.input.keyword] Processing output 'alfred.workflow.action.script' with arg ‘'
```

It looks like you have selected a keyword here... 
Can you do it again but for ```all objects in the workflow```, like this:

![screenshot_2015-03-03_12 19 41](https://cloud.githubusercontent.com/assets/4061923/6461390/bf34b758-c19f-11e4-8800-3cc568713609.png)

**Comment by deusy** [comment] 2015-03-04 08:52
That’s what I did before, and I’ve just double checked it. 'Interesting information' turns up with nothing, and 'All information' turns up as follows:

**Comment by deusy** [comment] 2015-03-04 10:48
I’ve also realised that when I lookup current artist online, I get a similar result to the lyrics search. It seems to be any command that searches the web.

**Comment by vdesabou** [comment] 2015-03-04 11:54
>That’s what I did before, and I’ve just double checked it. 'Interesting information' turns up with nothing, and 'All information' turns up as follows:

So empty ?

Are you using a proxy by any chance? If that's the case, you should maybe activate this in Advanced settings:

![pic](https://cloud.githubusercontent.com/assets/4061923/6483116/8b1c60f0-c26d-11e4-9737-c3cc84e907cf.png)

**Comment by vdesabou** [comment] 2015-03-04 18:58
Another question, when you created or updated your library, were you using
same network ?

Can you add an album or playlist in your library and check that artworks
are downloaded correctly? (on same network where you have lyrics and lookup
current artist online)

**Comment by deusy** [comment] 2015-03-05 06:08
I’m not using a proxy, so that isn’t the problem.

I downloaded the artworks for a new album without any problems, but the lyric and current artist search still don’t work for those songs. I did everything on the one wifi network.

**Comment by vdesabou** [comment] 2015-03-05 08:42
Ok, thanks for the feedback.

Can you install this version here http://inft.ly/aYvNGGa and then open debug window in alfred (choose ``All information```this time), execute the two commands which are causing issues and then copy/paste the output here ?

Thanks

**Comment by deusy** [comment] 2015-03-06 07:58
Lyric search turns up exactly the same, and current artist search turns up the following:

[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0" encoding="UTF-8"?>
<items><item arg="" valid="no"><arg></arg><title>Search for music in "Your Music" and your 7 playlists</title><subtitle>Begin typing at least 3 characters to start search in your 298 tracks ● ⚡ Quick Mode is active</subtitle><icon>./images/search.png</icon><text></text></item><item arg="" valid="no" autocomplete="Current Track▹"><arg></arg><title>Current Track</title><subtitle>Display current track information and browse various options</subtitle><icon>./images/current_track.png</icon><text></text></item><item arg="" valid="no" autocomplete="Play Queue▹"><arg></arg><title>Play Queue</title><subtitle>Get the current play queue. Always use the workflow to launch tracks, otherwise play queue will be empty</subtitle><icon>./images/play_queue.png</icon><text></text></item><item arg="a:16:{i:0;s:0:&quot;&quot;;i:1;s:0:&quot;&quot;;i:2;s:0:&quot;&quot;;i:3;s:0:&quot;&quot;;i:4;s:0:&quot;&quot;;i:5;s:0:&quot;&quot;;i:6;s:0:&quot;&quot;;i:7;s:21:&quot;lookup_current_artist&quot;;i:8;s:0:&quot;&quot;;i:9;s:0:&quot;&quot;;i:10;s:0:&quot;&quot;;i:11;s:0:&quot;&quot;;i:12;s:0:&quot;&quot;;i:13;s:0:&quot;&quot;;i:14;s:0:&quot;&quot;;i:15;s:0:&quot;&quot;;}" valid="yes"><arg>a:16:{i:0;s:0:"";i:1;s:0:"";i:2;s:0:"";i:3;s:0:"";i:4;s:0:"";i:5;s:0:"";i:6;s:0:"";i:7;s:21:"lookup_current_artist";i:8;s:0:"";i:9;s:0:"";i:10;s:0:"";i:11;s:0:"";i:12;s:0:"";i:13;s:0:"";i:14;s:0:"";i:15;s:0:"";}</arg><title>Lookup Current Artist online</title><subtitle>☁︎ Query all albums/tracks from current artist online..</subtitle><subtitle mod="alt">Not Available</subtitle><subtitle mod="cmd">Not Available</subtitle><subtitle mod="shift">Not Available</subtitle><subtitle mod="fn">Not Available</subtitle><subtitle mod="ctrl">Not Available</subtitle><icon>./images/online_artist.png</icon><text></text></item><item arg="" valid="no" autocomplete="Search Online▹"><arg></arg><title>Search online</title><subtitle>☁︎ You can search tracks, artists, albums and playlists online, i.e not in your library</subtitle><icon>./images/online.png</icon><text></text></item><item arg="" valid="no" autocomplete="Alfred Playlist▹Set Alfred Playlist▹"><arg></arg><title>Alfred Playlist ● not set</title><subtitle>Choose one of your playlists and add tracks, album, playlist to it directly from the workflow</subtitle><icon>./images/alfred_playlist.png</icon><text></text></item><item arg="" valid="no" autocomplete="Playlist▹"><arg></arg><title>Playlists</title><subtitle>Browse by playlist (7 playlists)</subtitle><icon>./images/playlists.png</icon><text></text></item><item arg="" valid="no" autocomplete="Your Music▹"><arg></arg><title>Your Music</title><subtitle>Browse Your Music (0 tracks ● 0  albums ● 0 artists)</subtitle><icon>./images/yourmusic.png</icon><text></text></item><item arg="" valid="no" autocomplete="Artist▹"><arg></arg><title>Artists</title><subtitle>Browse by artist (125 artists)</subtitle><icon>./images/artists.png</icon><text></text></item><item arg="" valid="no" autocomplete="Album▹"><arg></arg><title>Albums</title><subtitle>Browse by album (192 albums)</subtitle><icon>./images/albums.png</icon><text></text></item><item arg="" valid="no" autocomplete="Browse▹"><arg></arg><title>Browse</title><subtitle>Browse Spotify by categories, as in the Spotify player’s “Browse” tab</subtitle><icon>./images/browse.png</icon><text></text></item><item arg="" valid="no" autocomplete="Settings▹"><arg></arg><title>Settings</title><subtitle>User=deusy, Search scope=&lt;All&gt;, Max results=&lt;50&gt;, Controlling &lt;Alfred Playlist&gt;, Radio tracks=&lt;30&gt;</subtitle><icon>./images/settings.png</icon><text></text></item></items>
[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0" encoding="UTF-8"?>
<items><item arg="" valid="no"><arg></arg><title>Search for music in "Your Music" and your 7 playlists</title><subtitle>Begin typing at least 3 characters to start search in your 298 tracks ● ⚡ Quick Mode is active</subtitle><icon>./images/search.png</icon><text></text></item><item arg="" valid="no" autocomplete="Current Track▹"><arg></arg><title>Current Track</title><subtitle>Display current track information and browse various options</subtitle><icon>./images/current_track.png</icon><text></text></item><item arg="" valid="no" autocomplete="Play Queue▹"><arg></arg><title>Play Queue</title><subtitle>Get the current play queue. Always use the workflow to launch tracks, otherwise play queue will be empty</subtitle><icon>./images/play_queue.png</icon><text></text></item><item arg="a:16:{i:0;s:0:&quot;&quot;;i:1;s:0:&quot;&quot;;i:2;s:0:&quot;&quot;;i:3;s:0:&quot;&quot;;i:4;s:0:&quot;&quot;;i:5;s:0:&quot;&quot;;i:6;s:0:&quot;&quot;;i:7;s:21:&quot;lookup_current_artist&quot;;i:8;s:0:&quot;&quot;;i:9;s:0:&quot;&quot;;i:10;s:0:&quot;&quot;;i:11;s:0:&quot;&quot;;i:12;s:0:&quot;&quot;;i:13;s:0:&quot;&quot;;i:14;s:0:&quot;&quot;;i:15;s:0:&quot;&quot;;}" valid="yes"><arg>a:16:{i:0;s:0:"";i:1;s:0:"";i:2;s:0:"";i:3;s:0:"";i:4;s:0:"";i:5;s:0:"";i:6;s:0:"";i:7;s:21:"lookup_current_artist";i:8;s:0:"";i:9;s:0:"";i:10;s:0:"";i:11;s:0:"";i:12;s:0:"";i:13;s:0:"";i:14;s:0:"";i:15;s:0:"";}</arg><title>Lookup Current Artist online</title><subtitle>☁︎ Query all albums/tracks from current artist online..</subtitle><subtitle mod="alt">Not Available</subtitle><subtitle mod="cmd">Not Available</subtitle><subtitle mod="shift">Not Available</subtitle><subtitle mod="fn">Not Available</subtitle><subtitle mod="ctrl">Not Available</subtitle><icon>./images/online_artist.png</icon><text></text></item><item arg="" valid="no" autocomplete="Search Online▹"><arg></arg><title>Search online</title><subtitle>☁︎ You can search tracks, artists, albums and playlists online, i.e not in your library</subtitle><icon>./images/online.png</icon><text></text></item><item arg="" valid="no" autocomplete="Alfred Playlist▹Set Alfred Playlist▹"><arg></arg><title>Alfred Playlist ● not set</title><subtitle>Choose one of your playlists and add tracks, album, playlist to it directly from the workflow</subtitle><icon>./images/alfred_playlist.png</icon><text></text></item><item arg="" valid="no" autocomplete="Playlist▹"><arg></arg><title>Playlists</title><subtitle>Browse by playlist (7 playlists)</subtitle><icon>./images/playlists.png</icon><text></text></item><item arg="" valid="no" autocomplete="Your Music▹"><arg></arg><title>Your Music</title><subtitle>Browse Your Music (0 tracks ● 0  albums ● 0 artists)</subtitle><icon>./images/yourmusic.png</icon><text></text></item><item arg="" valid="no" autocomplete="Artist▹"><arg></arg><title>Artists</title><subtitle>Browse by artist (125 artists)</subtitle><icon>./images/artists.png</icon><text></text></item><item arg="" valid="no" autocomplete="Album▹"><arg></arg><title>Albums</title><subtitle>Browse by album (192 albums)</subtitle><icon>./images/albums.png</icon><text></text></item><item arg="" valid="no" autocomplete="Browse▹"><arg></arg><title>Browse</title><subtitle>Browse Spotify by categories, as in the Spotify player’s “Browse” tab</subtitle><icon>./images/browse.png</icon><text></text></item><item arg="" valid="no" autocomplete="Settings▹"><arg></arg><title>Settings</title><subtitle>User=deusy, Search scope=&lt;All&gt;, Max results=&lt;50&gt;, Controlling &lt;Alfred Playlist&gt;, Radio tracks=&lt;30&gt;</subtitle><icon>./images/settings.png</icon><text></text></item></items>
[ERROR: alfred.workflow.input.scriptfilter] Code 15: <?xml version="1.0" encoding="UTF-8"?>
<items><item arg="" valid="no"><arg></arg><title>Search for music in "Your Music" and your 7 playlists</title><subtitle>Begin typing at least 3 characters to start search in your 298 tracks ● ⚡ Quick Mode is active</subtitle><icon>./images/search.png</icon><text></text></item><item arg="" valid="no" autocomplete="Current Track▹"><arg></arg><title>Current Track</title><subtitle>Display current track information and browse various options</subtitle><icon>./images/current_track.png</icon><text></text></item><item arg="" valid="no" autocomplete="Play Queue▹"><arg></arg><title>Play Queue</title><subtitle>Get the current play queue. Always use the workflow to launch tracks, otherwise play queue will be empty</subtitle><icon>./images/play_queue.png</icon><text></text></item><item arg="a:16:{i:0;s:0:&quot;&quot;;i:1;s:0:&quot;&quot;;i:2;s:0:&quot;&quot;;i:3;s:0:&quot;&quot;;i:4;s:0:&quot;&quot;;i:5;s:0:&quot;&quot;;i:6;s:0:&quot;&quot;;i:7;s:21:&quot;lookup_current_artist&quot;;i:8;s:0:&quot;&quot;;i:9;s:0:&quot;&quot;;i:10;s:0:&quot;&quot;;i:11;s:0:&quot;&quot;;i:12;s:0:&quot;&quot;;i:13;s:0:&quot;&quot;;i:14;s:0:&quot;&quot;;i:15;s:0:&quot;&quot;;}" valid="yes"><arg>a:16:{i:0;s:0:"";i:1;s:0:"";i:2;s:0:"";i:3;s:0:"";i:4;s:0:"";i:5;s:0:"";i:6;s:0:"";i:7;s:21:"lookup_current_artist";i:8;s:0:"";i:9;s:0:"";i:10;s:0:"";i:11;s:0:"";i:12;s:0:"";i:13;s:0:"";i:14;s:0:"";i:15;s:0:"";}</arg><title>Lookup Current Artist online</title><subtitle>☁︎ Query all albums/tracks from current artist online..</subtitle><subtitle mod="alt">Not Available</subtitle><subtitle mod="cmd">Not Available</subtitle><subtitle mod="shift">Not Available</subtitle><subtitle mod="fn">Not Available</subtitle><subtitle mod="ctrl">Not Available</subtitle><icon>./images/online_artist.png</icon><text></text></item><item arg="" valid="no" autocomplete="Search Online▹"><arg></arg><title>Search online</title><subtitle>☁︎ You can search tracks, artists, albums and playlists online, i.e not in your library</subtitle><icon>./images/online.png</icon><text></text></item><item arg="" valid="no" autocomplete="Alfred Playlist▹Set Alfred Playlist▹"><arg></arg><title>Alfred Playlist ● not set</title><subtitle>Choose one of your playlists and add tracks, album, playlist to it directly from the workflow</subtitle><icon>./images/alfred_playlist.png</icon><text></text></item><item arg="" valid="no" autocomplete="Playlist▹"><arg></arg><title>Playlists</title><subtitle>Browse by playlist (7 playlists)</subtitle><icon>./images/playlists.png</icon><text></text></item><item arg="" valid="no" autocomplete="Your Music▹"><arg></arg><title>Your Music</title><subtitle>Browse Your Music (0 tracks ● 0  albums ● 0 artists)</subtitle><icon>./images/yourmusic.png</icon><text></text></item><item arg="" valid="no" autocomplete="Artist▹"><arg></arg><title>Artists</title><subtitle>Browse by artist (125 artists)</subtitle><icon>./images/artists.png</icon><text></text></item><item arg="" valid="no" autocomplete="Album▹"><arg></arg><title>Albums</title><subtitle>Browse by album (192 albums)</subtitle><icon>./images/albums.png</icon><text></text></item><item arg="" valid="no" autocomplete="Browse▹"><arg></arg><title>Browse</title><subtitle>Browse Spotify by categories, as in the Spotify player’s “Browse” tab</subtitle><icon>./images/browse.png</icon><text></text></item><item arg="" valid="no" autocomplete="Settings▹"><arg></arg><title>Settings</title><subtitle>User=deusy, Search scope=&lt;All&gt;, Max results=&lt;50&gt;, Controlling &lt;Alfred Playlist&gt;, Radio tracks=&lt;30&gt;</subtitle><icon>./images/settings.png</icon><text></text></item></items>
[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0" encoding="UTF-8"?>
<items><item arg="a:16:{i:0;s:0:&quot;&quot;;i:1;s:0:&quot;&quot;;i:2;s:0:&quot;&quot;;i:3;s:0:&quot;&quot;;i:4;s:0:&quot;&quot;;i:5;s:0:&quot;&quot;;i:6;s:0:&quot;&quot;;i:7;s:21:&quot;lookup_current_artist&quot;;i:8;s:0:&quot;&quot;;i:9;s:0:&quot;&quot;;i:10;s:0:&quot;&quot;;i:11;s:0:&quot;&quot;;i:12;s:0:&quot;&quot;;i:13;s:0:&quot;&quot;;i:14;s:0:&quot;&quot;;i:15;s:0:&quot;&quot;;}" valid="yes"><arg>a:16:{i:0;s:0:"";i:1;s:0:"";i:2;s:0:"";i:3;s:0:"";i:4;s:0:"";i:5;s:0:"";i:6;s:0:"";i:7;s:21:"lookup_current_artist";i:8;s:0:"";i:9;s:0:"";i:10;s:0:"";i:11;s:0:"";i:12;s:0:"";i:13;s:0:"";i:14;s:0:"";i:15;s:0:"";}</arg><title>Lookup Current Artist online</title><subtitle>☁︎ Query all albums/tracks from current artist online..</subtitle><subtitle mod="alt">Not Available</subtitle><subtitle mod="cmd">Not Available</subtitle><subtitle mod="shift">Not Available</subtitle><subtitle mod="fn">Not Available</subtitle><subtitle mod="ctrl">Not Available</subtitle><icon>./images/online_artist.png</icon><text></text></item><item arg="" valid="no" autocomplete="Current Track▹"><arg></arg><title>Current Track</title><subtitle>Display current track information and browse various options</subtitle><icon>./images/tracks.png</icon><text></text></item><item arg="a:16:{i:0;s:0:&quot;&quot;;i:1;s:0:&quot;&quot;;i:2;s:0:&quot;&quot;;i:3;s:0:&quot;&quot;;i:4;s:0:&quot;&quot;;i:5;s:0:&quot;&quot;;i:6;s:0:&quot;&quot;;i:7;s:7:&quot;current&quot;;i:8;s:0:&quot;&quot;;i:9;s:0:&quot;&quot;;i:10;s:0:&quot;&quot;;i:11;s:0:&quot;&quot;;i:12;s:0:&quot;&quot;;i:13;s:0:&quot;&quot;;i:14;s:0:&quot;&quot;;i:15;s:0:&quot;&quot;;}" valid="yes"><arg>a:16:{i:0;s:0:"";i:1;s:0:"";i:2;s:0:"";i:3;s:0:"";i:4;s:0:"";i:5;s:0:"";i:6;s:0:"";i:7;s:7:"current";i:8;s:0:"";i:9;s:0:"";i:10;s:0:"";i:11;s:0:"";i:12;s:0:"";i:13;s:0:"";i:14;s:0:"";i:15;s:0:"";}</arg><title>Get Current Track info</title><subtitle>Get current track information</subtitle><icon>./images/info.png</icon><text></text></item><item arg="help" valid="no"><arg>help</arg><title>There is no result for your search</title><subtitle></subtitle><icon>./images/warning.png</icon><text></text></item><item arg="a:16:{i:0;s:0:&quot;&quot;;i:1;s:0:&quot;&quot;;i:2;s:0:&quot;&quot;;i:3;s:0:&quot;&quot;;i:4;s:45:&quot;activate (open location &quot;spotify:search:cur&quot;)&quot;;i:5;s:0:&quot;&quot;;i:6;s:0:&quot;&quot;;i:7;s:0:&quot;&quot;;i:8;s:0:&quot;&quot;;i:9;s:0:&quot;&quot;;i:10;s:0:&quot;&quot;;i:11;s:0:&quot;&quot;;i:12;s:0:&quot;&quot;;i:13;s:0:&quot;&quot;;i:14;s:0:&quot;&quot;;i:15;s:0:&quot;&quot;;}" valid="yes"><arg>a:16:{i:0;s:0:"";i:1;s:0:"";i:2;s:0:"";i:3;s:0:"";i:4;s:45:"activate (open location "spotify:search:cur")";i:5;s:0:"";i:6;s:0:"";i:7;s:0:"";i:8;s:0:"";i:9;s:0:"";i:10;s:0:"";i:11;s:0:"";i:12;s:0:"";i:13;s:0:"";i:14;s:0:"";i:15;s:0:"";}</arg><title>Search for cur in Spotify</title><subtitle>This will start a new search in Spotify</subtitle><subtitle mod="alt">Not Available</subtitle><subtitle mod="cmd">Not Available</subtitle><subtitle mod="shift">Not Available</subtitle><subtitle mod="fn">Not Available</subtitle><subtitle mod="ctrl">Not Available</subtitle><icon>./images/spotify.png</icon><text></text></item><item arg="" valid="no" autocomplete="Search Online▹cur"><arg></arg><title>Search for cur online</title><subtitle>This will search online, i.e not in your library</subtitle><subtitle mod="alt">Not Available</subtitle><subtitle mod="cmd">Not Available</subtitle><subtitle mod="shift">Not Available</subtitle><subtitle mod="fn">Not Available</subtitle><subtitle mod="ctrl">Not Available</subtitle><icon>./images/online.png</icon><text></text></item></items>
[INFO: alfred.workflow.input.scriptfilter] Processing output 'alfred.workflow.action.script' with arg 'a:16:{i:0;s:0:"";i:1;s:0:"";i:2;s:0:"";i:3;s:0:"";i:4;s:0:"";i:5;s:0:"";i:6;s:0:"";i:7;s:21:"lookup_current_artist";i:8;s:0:"";i:9;s:0:"";i:10;s:0:"";i:11;s:0:"";i:12;s:0:"";i:13;s:0:"";i:14;s:0:"";i:15;s:0:"";}'

**Comment by vdesabou** [comment] 2015-03-06 10:01
The problem is this:

```
[ERROR: alfred.workflow.input.scriptfilter] Code 15: 
```

Can you do this:

-```spot_mini_debug```and choose _Browse to Alfred workflow folder_
-Open the directory in a terminal
-Type command ```./src/track_info.ksh``` and provide output.

Example:

```
./src/track_info.ksh
Stolen Dance▹Milky Chance▹Stolen Dance▹playing▹spotify:track:2p0Gd0LBUpqJkUC8ISdBjL▹316▹59
```

**Comment by deusy** [comment] 2015-03-06 23:48
Hey, sorry, I’m not sure what I’m meant to do. I browsed to the Alfred workflow folder and then dragged that folder to Terminal. Where do I go from there?

**Comment by vdesabou** [comment] 2015-03-07 13:23
Ok forget it, we'll do differently.

1/ Can you install this version http://inft.ly/D2hyqY7
2/ Then invoke any track, 2 or 3 times, and invoke Current Track
3/ Follow instructions from [here](http://alfred-spotify-mini-player.com/articles/support/) and send me the generated TGZ file.

Thanks for your help

**Comment by vdesabou** [comment] 2015-03-12 10:32
Hi,

Can you try this Beta release instead http://inft.ly/RjtbeCh ?
I've added some more AppleScript Error detections (issue https://github.com/vdesabou/alfred-spotify-mini-player/issues/67) that should help in your case..

Thanks

**Comment by vdesabou** [comment] 2015-03-18 12:59
any feedback @deusy ?
Thanks

**Comment by vdesabou** [comment] 2015-03-24 09:00
Closing. No feedback.

**Closed by vdesabou** 2015-03-24 09:00 UTC
Labels: wontfix

**Comment by Athosone** [comment] 2016-05-02 12:17
Got the same problem:
[ERROR: alfred.workflow.input.scriptfilter] XML Parse Error 'The operation couldn’t be completed. (NSXMLParserErrorDomain error 64.)'. Row (null), Col (null): 'XML declaration allowed only at the start of the document' in XML:
<?xml version="1.0" encoding="UTF-8"?>
<items><item arg="help" valid="no"><arg>help</arg><title>No lyrics found!</title><subtitle></subtitle><icon>./images/warning.png</icon><text></text></item></items>
<?xml version="1.0" encoding="UTF-8"?>
<items><item arg="help" valid="no"><arg>help</arg><title>No lyrics found!</title><subtitle></subtitle><icon>./images/warning.png</icon><text></text></item></items>
