### ISSUE TITLE
Now Playing Notification is disabled, yet notifications still appear. 

### ISSUE THREAD

**Issue by benwoodward** [vdesabou/alfred-spotify-mini-player#276] opened 2019-03-15 02:21 UTC
![image](https://user-images.githubusercontent.com/1472981/54403596-abe7ca00-4724-11e9-8d89-1621ba078c2a.png)

JSON via debug window: 

```json
    {
      "arg": "",
      "autocomplete": "Settings▹",
      "icon": {
        "path": "./images/settings.png"
      },
      "mods": {
        "alt": {
          "arg": "",
          "subtitle": "Not Available",
          "valid": "true"
        },
        "cmd": {
          "arg": "",
          "subtitle": "Not Available",
          "valid": "true"
        },
        "ctrl": {
          "arg": "",
          "subtitle": "Not Available",
          "valid": "true"
        },
        "fn": {
          "arg": "",
          "subtitle": "Not Available",
          "valid": "true"
        },
        "shift": {
          "arg": "",
          "subtitle": "Not Available",
          "valid": "true"
        }
      },
      "subtitle": "User=omitted, Search scope=<All>, Max results=<50>, Controlling <Alfred Playlist> Radio tracks=<30>",
      "text": null,
      "title": "Settings",
      "valid": "no"
    }
```

**Comment by vdesabou** [comment] 2019-03-15 07:11
Everything should be explained in this article http://alfred-spotify-mini-player.com/articles/now-playing/

Now Playing notifications are the ones that appear with track information when a track is changing.

If you want to get rid of all notifications, you need to disable it in OSX preferences as explained in article

Moreover, there is also a way to reduce the number of notifications (variable reduce_notifications), also explained in article

**Comment by scorchio** [comment] 2019-06-03 14:02
@vdesabou I think the article linked above is a bit misleading - I had to disable the notifications coming from "alerter", not from "Spotify Mini Player" in macOS preferences.

**Comment by vdesabou** [comment] 2019-06-04 09:43
@scorchio That's weird, on my side I don't see the alerter in preferences, and i can confirm it works by changing settings on "Spotify Mini Player"

![Screenshot 2019-06-04 at 11 42 44](https://user-images.githubusercontent.com/4061923/58869118-e75bba00-86bd-11e9-9bfe-ccba9bab9246.png)

**Comment by jessejanderson** [comment] 2019-06-06 19:34
@vdesabou I had the same experience as @scorchio. `Spotify Mini Player` isn't listed in my Notifications but `alerter` was and I was able to make the changes there which worked.

I'm on macOS Mojave 10.14.5, Alfred 4.0.1 b1078, and I was using an older version of the mini-player workflow but for 8.0 I just removed the old workflow completely and added v8.0 (going through the api authentication process again).

I haven't restarted my computer any time recently so it's possible the a restart would add `Spotify Mini Player` to the Notifications list?

**Comment by Kiszaner** [comment] 2019-06-08 10:34
Same here under same system and versions as @jessejanderson described.
The only difference is that I'm using a fresh installation without previous existing workflows.

**Comment by vdesabou** [comment] 2019-06-12 10:18
@jessejanderson @Kiszaner Did you change the workflow theme at some point ?

**Comment by jessejanderson** [comment] 2019-06-12 18:37
@vdesabou No.

**Comment by vdesabou** [comment] 2019-06-13 08:19
@Kiszaner @jessejanderson @scorchio 
Can you try to install the beta here https://transfer.sh/123KRd/spotifyminiplayer-beta.alfredworkflow

Then do the following:
-Disable "Now playing" notifications in workflow settings
-Enable "Now playing" notifications in workflow settings
-Go in Notification center OSX preferences and normally you should see a "Spotify Mini Player" entry

Keep me posted

**Comment by jessejanderson** [comment] 2019-06-19 16:56
@vdesabou I installed the beta and when I Enabled/Disabled "Now playing" notifications, I got the macOS security notice "Spotify Mini Player.app can't be opened because it is from an unidentified developer." But I also got the notification of those settings changing.

I do not see "Spotify Mini Player" in my Preferences::Notifications, presumably because of the security notice.

**Comment by Kiszaner** [comment] 2019-06-21 16:29
@vdesabou I tried the beta and indeed now there is a Spotify Mini Player entry on Notifications settings, but it didn’t solve the main issue and some other arose:
- Keeping Spotify Mini Player notifications as Banners on MacOS settings: it doesn't matter the Enable/Disable Now Playing command on Alfred, it always displays the notification as a banner.
- Keeping Spotify Mini Player notifications as Banners on MacOS settings and Enable Now Playing activated on Alfred: whenever I use a command that changes the track, an icon with the logo of Spotify Mini Player appears briefly on the Dock, then disappears. This causes a brief focus lost on the app currently on top, and if this app is Alfred, it closes the search bar. Very annoying.
- Disabling Spotify Mini Player notifications on MacOS settings partially works, at least it doesn’t show the notifications as a banner, but in Notification Center it keeps showing them and in duplicate. This behavior also happens on the previous cases, no matter which combination of settings are enabled.

Hope this feedback is helpful.

**Comment by vdesabou** [comment] 2019-06-28 07:47
@Kiszaner Thanks a lot for this feedback, it helps a lot !

Can you install this specific beta: https://transfer.sh/VWqAn/spotifyminiplayer-beta.alfredworkflow

1st: I cannot reproduce
2nd: This should be fixed now
3rd: This should be fixed now

Let me know what you have on your side after installing the beta

**Comment by vdesabou** [comment] 2019-07-01 05:08
8.1 is out. Please re-open other issue if you still get problems with notifications

**Closed by vdesabou** 2019-07-01 05:08 UTC
